name: Windows
on:
  release:
    types: [published]
  push:
    paths-ignore:
      - '.github/workflows/linux.yml'
      - '.github/workflows/macos.yml'

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: verify format
        run: make clang-format-check
  windows:
    needs: lint
    runs-on: windows-2022
    strategy:
      fail-fast: false
      matrix:
        build-type:
          - Debug
          - Release

    steps:
      - uses: actions/checkout@v3
      - name: Configure CMake
        run: >
          cmake -S . -B ./build
          -DCMAKE_BUILD_TYPE:STRING=${{matrix.build-type}}
          -DSIMPLE_CPP_XML_WARNINGS_AS_ERRORS:BOOL=ON
      - name: Build
        run: cmake --build ./build --config ${{matrix.build-type}} -- /m
      - name: Test
        working-directory: ./build
        run: ctest . --output-on-failure -C ${{matrix.build-type}}